package builder

import (
	"strings"

	"github.com/chrisdruta/vibe-tui-box/internal/schema"
)

// install.go generates the engine-authored Dockerfile that bakes
// image.agents and image.toolchains into a project's tools image. The
// recipes are the v2 continuation of the v1 image's install ARGs; they
// are engine code, never project input, so tools builds need no
// per-digest operator approval — the manifest only selects from this
// closed set.

// Engine-owned install pins. Claude and grok deliberately float on
// their installers' stable/latest channel (the one consciously mutable
// component); everything else moves only with engine releases.
// Version-lock machinery beyond these pins is deferred by decision
// record (BACKLOG.md).
const (
	claudeChannel = "stable"
	codexVersion  = "0.144.1"
	nodeMajor     = "22"
	bunVersion    = "1.3.14"
	rokitVersion  = "1.2.0"
	goVersion     = "1.26.5"
	goSHA256AMD64 = "5c2c3b16caefa1d968a94c1daca04a7ca301a496d9b086e17ad77bb81393f053"
	goSHA256ARM64 = "fe4789e92b1f33358680864bbe8704289e7bb5fc207d80623c308935bd696d49"
)

// GenerateInstall renders the install Dockerfile for the given
// selection. The output is a pure function of the selection — canonical
// layer order, engine-pinned versions — so identical selections yield
// identical bytes and a warm Docker layer cache. The result always
// satisfies ValidateDockerfile. Nil means nothing to install.
func GenerateInstall(agents []schema.AgentKind, toolchains []schema.Toolchain) []byte {
	want := map[string]bool{}
	for _, a := range agents {
		want[string(a)] = true
	}
	for _, t := range toolchains {
		want[string(t)] = true
	}
	if len(want) == 0 {
		return nil
	}
	// codex is npm-distributed: it drags the node toolchain in.
	if want[string(schema.AgentCodex)] {
		want[string(schema.ToolchainNode)] = true
	}

	var b strings.Builder
	b.WriteString("# Generated by the vibe engine from image.agents / image.toolchains.\n")
	b.WriteString("# Not project input: regenerated every build, pins move with engine releases.\n")
	b.WriteString("ARG " + BaseImageArg + "\n")
	b.WriteString("FROM ${" + BaseImageArg + "}\n")

	if entries := pathEntries(want); len(entries) > 0 {
		b.WriteString("\nENV PATH=" + strings.Join(entries, ":") + ":${PATH}\n")
	}
	if layers := rootLayers(want); len(layers) > 0 {
		b.WriteString("\nUSER root\n")
		for _, l := range layers {
			b.WriteString("\n" + l)
		}
	}
	b.WriteString("\nUSER vscode\n")
	for _, l := range userLayers(want) {
		b.WriteString("\n" + l)
	}
	return []byte(b.String())
}

// wantsAgent reports whether the selection includes any agent CLI.
func wantsAgent(want map[string]bool) bool {
	return want[string(schema.AgentClaude)] || want[string(schema.AgentCodex)] || want[string(schema.AgentGrok)]
}

// pathEntries lists the bin directories the selection installs into,
// in fixed v1 PATH order. Node needs none: nodesource installs to
// /usr/bin.
func pathEntries(want map[string]bool) []string {
	var out []string
	if wantsAgent(want) {
		out = append(out, "/home/vscode/.local/bin")
	}
	if want[string(schema.ToolchainBun)] {
		out = append(out, "/home/vscode/.bun/bin")
	}
	if want[string(schema.ToolchainRokit)] {
		out = append(out, "/home/vscode/.rokit/bin")
	}
	if want[string(schema.ToolchainGo)] {
		out = append(out, "/usr/local/go/bin", "/home/vscode/go/bin")
	}
	return out
}

// rootLayers renders the layers that need root: the agent-state mount
// point, system toolchains, and apt dependencies. Fixed order:
// agent-state, tmux, go, node, rokit's unzip guard.
func rootLayers(want map[string]bool) []string {
	var out []string
	// The agent-state named volume mounts here; Docker initializes a
	// fresh volume from the image path, so baking the directory
	// vscode-owned is what makes the volume writable by the agent.
	out = append(out, `# Agent-state mount point: fresh named volumes inherit this ownership.
RUN mkdir -p /vibe/agent-state && chown vscode:vscode /vibe/agent-state
`)
	if wantsAgent(want) {
		// Distro packages, no pin (version-lock machinery deferred by
		// decision record). Apt's /usr/bin/tmux is the fixed path
		// App.Agent probes; jq feeds the statusline glue (never the
		// hot-path state hook).
		out = append(out, `# tmux carries the persistent agent session (docs/architecture.md (agent sessions));
# jq parses the Claude statusline JSON.
RUN apt-get update \
    && apt-get install -y --no-install-recommends tmux jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
`)
	}
	if want[string(schema.ToolchainGo)] {
		out = append(out, `# Go toolchain: official tarball pinned by version + per-arch checksum,
# upstream layout under /usr/local/go (PATH above carries its bin dirs).
RUN tmp="$(mktemp -d)" \
    && case "$(uname -m)" in \
         x86_64)  arch=amd64; sha="`+goSHA256AMD64+`" ;; \
         aarch64) arch=arm64; sha="`+goSHA256ARM64+`" ;; \
         *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;; \
       esac \
    && curl -fsSL -o "$tmp/go.tar.gz" "https://go.dev/dl/go`+goVersion+`.linux-${arch}.tar.gz" \
    && echo "${sha}  $tmp/go.tar.gz" | sha256sum -c - \
    && rm -rf /usr/local/go \
    && tar -C /usr/local -xzf "$tmp/go.tar.gz" \
    && rm -rf "$tmp"
`)
	}
	if want[string(schema.ToolchainNode)] {
		out = append(out, `# Node: required by npm-distributed agent CLIs and available standalone.
RUN curl -fsSL "https://deb.nodesource.com/setup_`+nodeMajor+`.x" | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
`)
	}
	if want[string(schema.ToolchainRokit)] {
		out = append(out, `# rokit ships as a zip; make sure unzip exists on lean bases.
RUN command -v unzip >/dev/null 2>&1 \
    || { apt-get update \
         && apt-get install -y --no-install-recommends unzip \
         && apt-get clean \
         && rm -rf /var/lib/apt/lists/*; }
`)
	}
	return out
}

// userLayers renders the layers that install as vscode into the home
// directory. Fixed order: agents (claude, codex, grok), then bun,
// rokit.
func userLayers(want map[string]bool) []string {
	var out []string
	if want[string(schema.AgentClaude)] {
		out = append(out, `# Claude Code: the installer's `+claudeChannel+` channel.
RUN curl -fsSL https://claude.ai/install.sh | bash -s -- `+claudeChannel+` \
    && test -x /home/vscode/.local/bin/claude
`)
	}
	if want[string(schema.AgentCodex)] {
		out = append(out, `RUN npm install -g --prefix /home/vscode/.local "@openai/codex@`+codexVersion+`"
`)
	}
	if want[string(schema.AgentGrok)] {
		out = append(out, `# Grok (xAI official). Its state (auth.json, config.toml) lives in
# ~/.grok with no env override, so ~/.grok is symlinked into the state
# volume BEFORE install. The installer symlinks grok/agent into
# GROK_BIN_DIR pointing at ~/.grok/downloads/, which the runtime volume
# mount would shadow — so the real binary is materialized instead.
RUN mkdir -p /home/vscode/.agents/grok \
    && ln -s /home/vscode/.agents/grok /home/vscode/.grok \
    && curl -fsSL https://x.ai/cli/install.sh | GROK_BIN_DIR=/home/vscode/.local/bin bash -s -- \
    && bin="$(readlink -f /home/vscode/.local/bin/grok)" \
    && rm -f /home/vscode/.local/bin/grok /home/vscode/.local/bin/agent \
    && cp "$bin" /home/vscode/.local/bin/grok \
    && ln -s grok /home/vscode/.local/bin/agent \
    && rm -rf /home/vscode/.agents/grok/downloads
`)
	}
	if want[string(schema.ToolchainBun)] {
		out = append(out, `RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v`+bunVersion+`" \
    && test -x /home/vscode/.bun/bin/bun
`)
	}
	if want[string(schema.ToolchainRokit)] {
		out = append(out, `RUN tmp="$(mktemp -d)" && cd "$tmp" \
    && curl -fsSL -o rokit.zip "https://github.com/rojo-rbx/rokit/releases/download/v`+rokitVersion+`/rokit-`+rokitVersion+`-linux-$(uname -m).zip" \
    && unzip -q rokit.zip \
    && ./rokit self-install \
    && rm -rf "$tmp"
`)
	}
	return out
}
