package builder

import (
	"strings"

	"github.com/chrisdruta/vibe-tui-box/internal/schema"
)

// install.go generates the engine-authored Dockerfile that bakes
// image.agents and image.toolchains into a project's tools image. The
// recipes are the v2 continuation of the v1 image's install ARGs; they
// are engine code, never project input, so tools builds need no
// per-digest operator approval — the manifest only selects from this
// closed set.

// Engine-owned install pins. Agent CLIs follow the manifest: an
// unversioned image.agents entry tracks its installer's channel below
// and re-pulls on every rebuild (the refresh path); a pinned entry
// ("claude@2.1.220") installs that exact version in a plain cached
// layer and never refreshes. The system toolchains move only with
// engine releases.
const (
	claudeChannel = "stable"
	codexChannel  = "latest" // the npm dist-tag unversioned codex tracks
	nodeMajor     = "22"
	bunVersion    = "1.3.14"
	rokitVersion  = "1.2.0"
	goVersion     = "1.26.5"
	goSHA256AMD64 = "5c2c3b16caefa1d968a94c1daca04a7ca301a496d9b086e17ad77bb81393f053"
	goSHA256ARM64 = "fe4789e92b1f33358680864bbe8704289e7bb5fc207d80623c308935bd696d49"
	// tmux is pinned and built from source — the lesson the v1 line
	// already recorded (its install-tmux.sh/Dockerfile carried the SAME
	// version + checksum): distro tmux drops sixel images on pane redraw
	// (bookworm ships 3.3a; upstream #4499/#4639 fixed by 3.7) and skews
	// per base image, while host conf and container scripts are written
	// against one version's semantics. The v2 cutover regressed this to
	// apt tmux; re-pinned 2026-07-25.
	tmuxVersion = "3.7b"
	tmuxSHA256  = "87f2e99e3b685973f2ca002ffd6ed7e51a5744f7009daae5a15670b6d532db96"
)

// AgentRefreshArg is the build arg that busts the Docker layer cache
// for the channel-tracking (unversioned) agent installers. Every `vibe
// rebuild` stamps it with a fresh value so those layers — and only
// those — re-run and re-pull the latest agent builds; pinned agents and
// the system toolchains sit in plain layers and stay cached. When a
// project has never rebuilt the arg is absent.
const AgentRefreshArg = "VIBE_AGENT_REFRESH"

// GenerateInstall renders the install Dockerfile for the given
// selection. The output is a pure function of the selection (and the
// refresh flag) — canonical layer order, engine-pinned toolchains,
// manifest-pinned or channel-tracking agents — so identical inputs
// yield identical bytes and a warm Docker layer cache. The result
// always satisfies ValidateDockerfile. Nil means nothing to install.
//
// refresh weaves the AgentRefreshArg cache-buster into the UNVERSIONED
// agent layers only; a manifest-pinned agent installs its exact version
// in a plain layer no refresh can move, and the system toolchains are
// never touched. A selection with only pinned agents ignores refresh
// entirely.
func GenerateInstall(agents []schema.AgentSpec, toolchains []schema.Toolchain, refresh bool) []byte {
	want := map[string]bool{}
	pin := map[schema.AgentKind]string{}
	for _, a := range agents {
		want[string(a.Kind)] = true
		pin[a.Kind] = a.Version
	}
	for _, t := range toolchains {
		want[string(t)] = true
	}
	if len(want) == 0 {
		return nil
	}
	// codex is npm-distributed: it drags the node toolchain in.
	if want[string(schema.AgentCodex)] {
		want[string(schema.ToolchainNode)] = true
	}

	var b strings.Builder
	b.WriteString("# Generated by the vibe engine from image.agents / image.toolchains.\n")
	b.WriteString("# Not project input: regenerated every build, pins move with engine releases.\n")
	b.WriteString("ARG " + BaseImageArg + "\n")
	b.WriteString("FROM ${" + BaseImageArg + "}\n")

	if entries := pathEntries(want); len(entries) > 0 {
		b.WriteString("\nENV PATH=" + strings.Join(entries, ":") + ":${PATH}\n")
	}
	if layers := rootLayers(want); len(layers) > 0 {
		b.WriteString("\nUSER root\n")
		for _, l := range layers {
			b.WriteString("\n" + l)
		}
	}
	b.WriteString("\nUSER vscode\n")
	for _, l := range userLayers(want, pin, refresh) {
		b.WriteString("\n" + l)
	}
	return []byte(b.String())
}

// wantsAgent reports whether the selection includes any agent CLI.
func wantsAgent(want map[string]bool) bool {
	return want[string(schema.AgentClaude)] || want[string(schema.AgentCodex)] || want[string(schema.AgentGrok)]
}

// pathEntries lists the bin directories the selection installs into,
// in fixed v1 PATH order. Node needs none: nodesource installs to
// /usr/bin.
func pathEntries(want map[string]bool) []string {
	var out []string
	if wantsAgent(want) {
		out = append(out, "/home/vscode/.local/bin")
	}
	if want[string(schema.ToolchainBun)] {
		out = append(out, "/home/vscode/.bun/bin")
	}
	if want[string(schema.ToolchainRokit)] {
		out = append(out, "/home/vscode/.rokit/bin")
	}
	if want[string(schema.ToolchainGo)] {
		out = append(out, "/usr/local/go/bin", "/home/vscode/go/bin")
	}
	return out
}

// rootLayers renders the layers that need root: the agent-state mount
// point, system toolchains, and apt dependencies. Fixed order:
// agent-state, tmux, go, node, rokit's unzip guard.
func rootLayers(want map[string]bool) []string {
	var out []string
	// The agent-state named volume mounts here; Docker initializes a
	// fresh volume from the image path, so baking the directory
	// vscode-owned is what makes the volume writable by the agent.
	out = append(out, `# Agent-state mount point: fresh named volumes inherit this ownership.
RUN mkdir -p /vibe/agent-state && chown vscode:vscode /vibe/agent-state
`)
	if wantsAgent(want) {
		// Pinned source build (see the tmuxVersion decision comment) at
		// /usr/local/bin/tmux — the path App.Agent probes first. Single
		// stage on purpose: ValidateDockerfile forbids extra build
		// stages, so the build deps stay in the image (a dev container
		// carries compilers anyway). jq feeds the statusline glue
		// (never the hot-path state hook).
		out = append(out, `# tmux `+tmuxVersion+` carries the persistent agent session (docs/architecture.md
# (agent sessions)): pinned source build with --enable-sixel — distro tmux
# drops sixel images on pane redraw and varies per base image. jq
# parses the Claude statusline JSON.
RUN apt-get update \
    && apt-get install -y --no-install-recommends jq build-essential byacc pkg-config libevent-dev libncurses-dev ca-certificates curl \
    && tmp="$(mktemp -d)" \
    && curl -fsSL -o "$tmp/tmux.tar.gz" "https://github.com/tmux/tmux/releases/download/`+tmuxVersion+`/tmux-`+tmuxVersion+`.tar.gz" \
    && echo "`+tmuxSHA256+`  $tmp/tmux.tar.gz" | sha256sum -c - \
    && tar -C "$tmp" -xzf "$tmp/tmux.tar.gz" \
    && cd "$tmp/tmux-`+tmuxVersion+`" \
    && ./configure --prefix=/usr/local --enable-sixel \
    && make -j"$(nproc)" \
    && make install \
    && cd / \
    && rm -rf "$tmp" \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
`)
	}
	if want[string(schema.ToolchainGo)] {
		out = append(out, `# Go toolchain: official tarball pinned by version + per-arch checksum,
# upstream layout under /usr/local/go (PATH above carries its bin dirs).
RUN tmp="$(mktemp -d)" \
    && case "$(uname -m)" in \
         x86_64)  arch=amd64; sha="`+goSHA256AMD64+`" ;; \
         aarch64) arch=arm64; sha="`+goSHA256ARM64+`" ;; \
         *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;; \
       esac \
    && curl -fsSL -o "$tmp/go.tar.gz" "https://go.dev/dl/go`+goVersion+`.linux-${arch}.tar.gz" \
    && echo "${sha}  $tmp/go.tar.gz" | sha256sum -c - \
    && rm -rf /usr/local/go \
    && tar -C /usr/local -xzf "$tmp/go.tar.gz" \
    && rm -rf "$tmp"
`)
	}
	if want[string(schema.ToolchainNode)] {
		out = append(out, `# Node: required by npm-distributed agent CLIs and available standalone.
RUN curl -fsSL "https://deb.nodesource.com/setup_`+nodeMajor+`.x" | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
`)
	}
	if want[string(schema.ToolchainRokit)] {
		out = append(out, `# rokit ships as a zip; make sure unzip exists on lean bases.
RUN command -v unzip >/dev/null 2>&1 \
    || { apt-get update \
         && apt-get install -y --no-install-recommends unzip \
         && apt-get clean \
         && rm -rf /var/lib/apt/lists/*; }
`)
	}
	return out
}

// refreshBust returns the shell prefix that ties a channel-tracking
// agent layer's cache key to the refresh token: after variable
// expansion the RUN text embeds the token value, so a new token misses
// the cache and re-runs the installer. Empty when not busting, which
// keeps that layer plainly cacheable.
func refreshBust(bust bool) string {
	if !bust {
		return ""
	}
	return `: "agents-refresh=${` + AgentRefreshArg + `}" \
    && `
}

// userLayers renders the layers that install as vscode into the home
// directory. Fixed order: agents (claude, codex, grok), then bun,
// rokit. Unversioned agents track their channel and, when refresh is
// set, gain the AgentRefreshArg cache-buster (declared once, up front);
// manifest-pinned agents install their exact version in a plain layer
// the buster never touches. bun and rokit stay engine-pinned but,
// sitting after the agents, re-run too when a refresh busts the chain
// (cheap — the expensive system toolchains live in rootLayers, before
// USER vscode).
func userLayers(want map[string]bool, pin map[schema.AgentKind]string, refresh bool) []string {
	bustFor := func(kind schema.AgentKind) bool {
		return refresh && pin[kind] == ""
	}
	anyBust := false
	for _, kind := range []schema.AgentKind{schema.AgentClaude, schema.AgentCodex, schema.AgentGrok} {
		if want[string(kind)] && bustFor(kind) {
			anyBust = true
		}
	}
	var out []string
	if anyBust {
		out = append(out, `# Agent refresh: this build arg's value (a fresh token per rebuild)
# is woven into the channel-tracking installers below so their Docker
# layer cache misses and re-pulls the latest builds. Pinned agents sit
# in plain layers it never reaches.
ARG `+AgentRefreshArg+`
`)
	}
	if want[string(schema.AgentClaude)] {
		target := claudeChannel + " channel"
		spec := claudeChannel
		if v := pin[schema.AgentClaude]; v != "" {
			target = "manifest-pinned " + v
			spec = v
		}
		out = append(out, `# Claude Code: the installer's `+target+`.
RUN `+refreshBust(bustFor(schema.AgentClaude))+`curl -fsSL https://claude.ai/install.sh | bash -s -- `+spec+` \
    && test -x /home/vscode/.local/bin/claude
`)
	}
	if want[string(schema.AgentCodex)] {
		// Unversioned tracks the npm dist-tag; a manifest pin is exact.
		codexSpec := codexChannel
		if v := pin[schema.AgentCodex]; v != "" {
			codexSpec = v
		}
		out = append(out, `RUN `+refreshBust(bustFor(schema.AgentCodex))+`npm install -g --prefix /home/vscode/.local "@openai/codex@`+codexSpec+`"
`)
	}
	if want[string(schema.AgentGrok)] {
		out = append(out, `# Grok (xAI official). Its state (auth.json, config.toml) lives in
# ~/.grok with no env override, so ~/.grok is symlinked into the state
# volume BEFORE install. The installer symlinks grok/agent into
# GROK_BIN_DIR pointing at ~/.grok/downloads/, which the runtime volume
# mount would shadow — so the real binary is materialized instead.
RUN `+refreshBust(bustFor(schema.AgentGrok))+`mkdir -p /home/vscode/.agents/grok \
    && ln -s /home/vscode/.agents/grok /home/vscode/.grok \
    && curl -fsSL https://x.ai/cli/install.sh | GROK_BIN_DIR=/home/vscode/.local/bin bash -s -- \
    && bin="$(readlink -f /home/vscode/.local/bin/grok)" \
    && rm -f /home/vscode/.local/bin/grok /home/vscode/.local/bin/agent \
    && cp "$bin" /home/vscode/.local/bin/grok \
    && ln -s grok /home/vscode/.local/bin/agent \
    && rm -rf /home/vscode/.agents/grok/downloads
`)
	}
	if want[string(schema.ToolchainBun)] {
		out = append(out, `RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v`+bunVersion+`" \
    && test -x /home/vscode/.bun/bin/bun
`)
	}
	if want[string(schema.ToolchainRokit)] {
		out = append(out, `RUN tmp="$(mktemp -d)" && cd "$tmp" \
    && curl -fsSL -o rokit.zip "https://github.com/rojo-rbx/rokit/releases/download/v`+rokitVersion+`/rokit-`+rokitVersion+`-linux-$(uname -m).zip" \
    && unzip -q rokit.zip \
    && ./rokit self-install \
    && rm -rf "$tmp"
`)
	}
	return out
}
