set -s default-terminal "tmux-256color"
set -as terminal-features ",xterm*:RGB"
set -s extended-keys on
set -as terminal-features ",xterm*:extkeys"
set -s escape-time 10
set -s focus-events on
set -g history-limit 50000
set -g mouse on
set -s set-clipboard on
set -g allow-passthrough on
